import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  categoriesFileSchema,
  contentFrontMatterSchema,
  fixtureSchema,
  manifestSchema,
  presetSchema,
  professionsFileSchema,
  reservedSlugsFileSchema,
  siteConfigSchema,
  synonymsFileSchema,
  tagsFileSchema,
} from '@mangotools/schemas';
import { z } from 'zod';
import type { PipelineOutput } from './pipeline.ts';

const EDITOR_SCHEMAS: Record<string, z.ZodType> = {
  manifest: manifestSchema,
  preset: presetSchema,
  fixture: fixtureSchema,
  'content-front-matter': contentFrontMatterSchema,
  categories: categoriesFileSchema,
  professions: professionsFileSchema,
  tags: tagsFileSchema,
  synonyms: synonymsFileSchema,
  'reserved-slugs': reservedSlugsFileSchema,
  'site-config': siteConfigSchema,
};

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

function write(path: string, text: string) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text, 'utf8');
}

export function engineLoadersSource(engineIds: string[]): string {
  const lines = engineIds.map(
    (id) =>
      `  ${JSON.stringify(id)}: () => import('../engines/${id}/src/index.ts').then((m) => m.engine),`,
  );
  return [
    '// Generated by `pnpm gen` from presets/. Do not edit.',
    "import type { EngineModule } from '@mangotools/core';",
    '',
    '/** Engine id → lazy loader. Used only inside the runtime worker. */',
    'export const engineLoaders: Readonly<Record<string, () => Promise<EngineModule>>> = {',
    ...lines,
    '};',
    '',
  ].join('\n');
}

/** Replaces generated/ with fresh outputs. */
export function writeOutputs(dir: string, output: PipelineOutput): string[] {
  rmSync(dir, { recursive: true, force: true });
  const written: string[] = [];
  const put = (rel: string, text: string) => {
    write(join(dir, rel), text);
    written.push(rel);
  };
  put('registry.json', json(output.registry));
  for (const [id, preset] of Object.entries(output.registry.presets))
    put(`presets/${id}.json`, json(preset));
  put('search-index.json', json(output.searchIndex));
  put('determinism-fixtures.json', json(output.determinism));
  put('engine-loaders.ts', engineLoadersSource(output.engineIds));
  writeSchemas(dir, put);
  return written;
}

export function writeSchemas(_dir: string, put: (rel: string, text: string) => void) {
  for (const [name, schema] of Object.entries(EDITOR_SCHEMAS)) {
    put(
      `schemas/${name}.json`,
      json(z.toJSONSchema(schema, { unrepresentable: 'any', io: 'input' })),
    );
  }
}
