/**
 * Interface text used by components. Tool-specific text lives in presets and content files;
 * this file holds only the shared chrome. Placeholders use {name}.
 */
export const EN = {
  'site.skip': 'Skip to content',
  'site.home': 'Home',
  'site.tools': 'Tools',
  'site.allTools': 'All tools',
  'site.mainNav': 'Main',
  'site.breadcrumb': 'Breadcrumb',
  'site.categories': 'Categories',
  'site.product': 'A MangoPie product',
  'site.homeLink': 'MangoTools home',
  'theme.label': 'Colour theme',
  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'theme.system': 'System',
  'theme.current': 'Theme: {theme}. Change theme',
  'search.label': 'Search tools',
  'search.placeholder': 'Search tools — try GST, JSON, Base64, URL',
  'search.noResults': 'No tools match “{query}”.',
  'search.count': '{count} tools found',
  'search.one': '1 tool found',
  'search.loading': 'Loading search…',
  'search.unavailable': 'Search is unavailable right now. Browse all tools instead.',
  'chips.label': 'Filter by category',
  'chips.all': 'All',
  'recent.title': 'Continue where you left off',
  'card.tools': '{count} tools',
  'card.tool': '1 tool',
  'card.pro': 'Professional',
  'privacy.badge': 'Runs on your device',
  'privacy.detail': 'Your data is processed in this browser and never uploaded.',
  'action.trySample': 'Try sample',
  'action.howToUse': 'How to use',
  'action.copy': 'Copy',
  'action.copyResult': 'Copy result',
  'action.download': 'Download',
  'action.print': 'Print',
  'action.reset': 'Reset',
  'action.swap': 'Swap',
  'action.swapLabel': 'Swap input and output and reverse the direction',
  'action.paste': 'Paste',
  'action.clear': 'Clear',
  'action.openFile': 'Open file',
  'action.goTo': 'Go to line {line}, column {column}',
  'action.showWorking': 'Show calculation',
  'toast.copied': 'Copied to clipboard.',
  'toast.copyFailed': 'Could not copy. Select the result and copy it manually.',
  'toast.pasteFailed': 'Could not read the clipboard. Paste with Ctrl+V or ⌘V instead.',
  'toast.fileTooLarge': 'That file is larger than 50 MB.',
  'toast.fileRead': 'Opened {name}.',
  'toast.downloaded': 'Downloaded {name}.',
  'input.label': 'Input',
  'input.stats': '{chars} characters · {bytes}',
  'output.label': 'Output',
  'output.empty': 'The result appears here as you type.',
  'status.valid': 'Valid',
  'status.ready': 'Ready',
  'status.working': 'Working…',
  'status.invalid': 'Not valid',
  'result.title': 'Result',
  'result.empty': 'Enter the values above to see the result.',
  'result.working': 'Calculating…',
  'result.missing': 'Enter {fields} to see the result.',
  'working.title': 'Calculation',
  'field.custom': 'Custom',
  'field.customValue': 'Custom {label}',
  'field.required': 'Required',
  'error.title': 'Please check the input',
  'disclaimer.title': 'Disclaimer',
  'disclaimer.professional':
    'Results are provided for guidance. Check them against the applicable rules and your professional judgement before relying on them.',
  'related.title': 'Related tools',
  'example.input': 'Input',
  'example.result': 'Result',
  'faq.title': 'Frequently asked questions',
} as const;

export type StringKey = keyof typeof EN;

/** Looks up interface text and fills {placeholders}. */
export function t(key: StringKey, vars: Record<string, string | number> = {}): string {
  return EN[key].replace(/\{(\w+)\}/g, (match, name: string) =>
    name in vars ? String(vars[name]) : match,
  );
}
