/**
 * Interface text used by components. Tool-specific text lives in presets and content files;
 * this file holds only the shared chrome. Placeholders use {name}.
 */
export const EN = {
  'site.skip': 'Skip to content',
  'site.home': 'Home',
  'site.tools': 'Tools',
  'site.allTools': 'All tools',
  'site.mainNav': 'Main',
  'site.breadcrumb': 'Breadcrumb',
  'site.categories': 'Categories',
  'site.info': 'Site information',
  'site.homeLink': 'BeyondTheAI home',
  'theme.label': 'Colour theme',
  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'theme.system': 'System',
  'theme.current': 'Theme: {theme}. Change theme',
  'search.label': 'Search tools',
  'search.open': 'Search tools',
  'search.close': 'Close search',
  'search.placeholder': 'Search tools — try GST, JSON, CBM, Base64',
  'search.noResults': 'No tools match “{query}”.',
  'search.count': '{count} tools found',
  'search.one': '1 tool found',
  'search.loading': 'Loading search…',
  'search.unavailable': 'Search is unavailable right now. Browse all tools instead.',
  'chips.label': 'Filter by category',
  'chips.all': 'All',
  'recent.title': 'Continue where you left off',
  'card.tools': '{count} tools',
  'card.tool': '1 tool',
  'card.pro': 'Professional',
  'privacy.badge': 'Runs on your device',
  'privacy.detail': 'Processed locally in your browser. Nothing is uploaded.',
  'action.trySample': 'Try sample',
  'action.howToUse': 'How to use',
  'action.copy': 'Copy',
  'action.copyResult': 'Copy result',
  'action.download': 'Download',
  'action.print': 'Print',
  'action.reset': 'Reset',
  'action.swap': 'Swap',
  'action.swapLabel': 'Swap input and output and reverse the direction',
  'action.paste': 'Paste',
  'action.clear': 'Clear',
  'action.openFile': 'Open file',
  'action.goTo': 'Go to line {line}, column {column}',
  'action.showWorking': 'Show calculation',
  'toast.copied': 'Copied to clipboard.',
  'toast.copyFailed': 'Could not copy. Select the result and copy it manually.',
  'toast.pasteFailed': 'Could not read the clipboard. Paste with Ctrl+V or ⌘V instead.',
  'toast.fileTooLarge': 'That file is larger than 50 MB.',
  'toast.fileRead': 'Opened {name}.',
  'toast.downloaded': 'Downloaded {name}.',
  'input.label': 'Input',
  'input.stats': '{chars} characters · {bytes}',
  'output.label': 'Output',
  'output.empty': 'The result appears here as you type.',
  'status.valid': 'Valid',
  'status.ready': 'Ready',
  'status.working': 'Working…',
  'status.invalid': 'Not valid',
  'result.title': 'Result',
  'result.empty': 'Enter the values above to see the result.',
  'result.working': 'Calculating…',
  'result.missing': 'Enter {fields} to see the result.',
  'working.title': 'Calculation',
  'field.custom': 'Custom',
  'field.customValue': 'Custom {label}',
  'field.required': 'Required',
  'field.help': 'Help',
  'error.title': 'Please check the input',
  'disclaimer.title': 'Disclaimer',
  'disclaimer.professional':
    'Results are provided for guidance. Check them against the applicable rules and your professional judgement before relying on them.',
  'fileTool.chooseFiles': 'Choose files',
  'fileTool.moveUp': 'Move {name} up',
  'fileTool.moveDown': 'Move {name} down',
  'fileTool.removeFile': 'Remove {name}',
  'fileTool.clearAll': 'Clear all',
  'fileTool.outputNameLabel': 'Output file name',
  'itemRows.itemLabel': 'Item {number}',
  'itemRows.addItem': 'Add item',
  'itemRows.removeItem': 'Remove item {number}',
  'itemRows.removeConfirm': 'Remove item {number} and its details?',
  'itemRows.rowError': 'Item {number} — {message}',
  'invoiceItems.maxReached': 'This invoice supports at most {max} items.',
  'packingItems.maxReached': 'This packing list supports at most {max} items.',
  'openings.row': 'Opening {number}',
  'openings.add': 'Add opening',
  'openings.remove': 'Remove {label}',
  'openings.removeShort': 'Remove',
  'openings.width': 'Width',
  'openings.height': 'Height',
  'openings.quantity': 'Quantity',
  'openings.max': 'You can add at most {max} rows.',
  'notes.assumptions': 'Assumptions used',
  'notes.about': 'About this estimate',
  'notes.important': 'Important notes',
  'related.title': 'Related tools',
  'example.input': 'Input',
  'example.result': 'Result',
  'faq.title': 'Frequently asked questions',
} as const;

export type StringKey = keyof typeof EN;

/** Looks up interface text and fills {placeholders}. */
export function t(key: StringKey, vars: Record<string, string | number> = {}): string {
  return EN[key].replace(/\{(\w+)\}/g, (match, name: string) =>
    name in vars ? String(vars[name]) : match,
  );
}
