import { describe, expect, it } from 'vitest';
import { createSearcher } from '../../engines/search/src/index.ts';
import { runPipeline } from '../../scripts/generate/pipeline.ts';
import { loadSources } from '../../scripts/generate/sources.ts';
import { loadEngines } from '../../scripts/lib/engines.ts';

const { output } = await runPipeline(loadSources().sources, await loadEngines());
if (!output) throw new Error('pnpm gen pipeline failed; run pnpm gen for details.');
const search = createSearcher(output.searchIndex.index);
const top = (q: string) => search(q, 3)[0]?.id;

describe('search relevance over the generated index', () => {
  const cases: [string, string][] = [
    ['JSON Formatter', 'json-formatter'],
    ['Base64 Encode & Decode', 'base64-encode-decode'],
    ['URL Encode & Decode', 'url-encode-decode'],
    ['CSV to JSON', 'csv-to-json'],
    ['csv to json', 'csv-to-json'],
    ['convert csv to json', 'csv-to-json'],
    ['csv to json online', 'csv-to-json'],
    ['csv to json array', 'csv-to-json'],
    ['csv to json objects', 'csv-to-json'],
    ['convert spreadsheet csv to json', 'csv-to-json'],
    ['free csv to json converter', 'csv-to-json'],
    ['browser csv to json', 'csv-to-json'],
    ['convert api json to csv', 'json-to-csv'],
    ['GST Calculator', 'gst-calculator'],
    ['Profit Margin Calculator', 'profit-margin-calculator'],
    ['gst', 'gst-calculator'],
    ['json beautifier', 'json-formatter'],
    ['jsn formatter', 'json-formatter'],
    ['b64', 'base64-encode-decode'],
    ['percent encoding', 'url-encode-decode'],
    ['urlencode', 'url-encode-decode'],
    ['cgst sgst', 'gst-calculator'],
    ['goods and services tax', 'gst-calculator'],
    ['gross margin', 'profit-margin-calculator'],
    ['Markup Calculator', 'markup-calculator'],
    ['markup', 'markup-calculator'],
    ['mark up', 'markup-calculator'],
    ['cost plus pricing', 'markup-calculator'],
    ['selling price from markup', 'markup-calculator'],
    ['selling price from margin', 'profit-margin-calculator'],
    ['CBM Calculator', 'cbm-calculator'],
    ['cbm', 'cbm-calculator'],
    ['cubic meter', 'cbm-calculator'],
    ['cubic metre', 'cbm-calculator'],
    ['carton volume', 'cbm-calculator'],
    ['cargo volume', 'cbm-calculator'],
    ['shipping volume', 'cbm-calculator'],
    ['Volumetric Weight Calculator', 'volumetric-weight-calculator'],
    ['volumetric weight', 'volumetric-weight-calculator'],
    ['dimensional weight', 'volumetric-weight-calculator'],
    ['courier weight', 'volumetric-weight-calculator'],
    ['chargeable weight', 'volumetric-weight-calculator'],
    ['shipping weight', 'volumetric-weight-calculator'],
    ['air freight weight', 'volumetric-weight-calculator'],
    ['dim weight', 'volumetric-weight-calculator'],
    ['Container Loading Calculator', 'container-loading-calculator'],
    ['container loading calculator', 'container-loading-calculator'],
    ['container capacity calculator', 'container-loading-calculator'],
    ['carton container calculator', 'container-loading-calculator'],
    ['how many cartons in a container', 'container-loading-calculator'],
    ['20ft container calculator', 'container-loading-calculator'],
    ['40ft container calculator', 'container-loading-calculator'],
    ['shipping container calculator', 'container-loading-calculator'],
    ['Pallet Loading Calculator', 'pallet-loading-calculator'],
    ['pallet loading calculator', 'pallet-loading-calculator'],
    ['pallet capacity calculator', 'pallet-loading-calculator'],
    ['carton pallet calculator', 'pallet-loading-calculator'],
    ['how many cartons on a pallet', 'pallet-loading-calculator'],
    ['euro pallet calculator', 'pallet-loading-calculator'],
    ['pallet planner', 'pallet-loading-calculator'],
    ['PDF Merge', 'pdf-merge'],
    ['pdf merge', 'pdf-merge'],
    ['merge pdf', 'pdf-merge'],
    ['combine pdf', 'pdf-merge'],
    ['pdf joiner', 'pdf-merge'],
    ['combine pdf files', 'pdf-merge'],
    ['merge pdf online', 'pdf-merge'],
    ['browser pdf merger', 'pdf-merge'],
    ['no upload pdf merge', 'pdf-merge'],
    ['JPG to PDF', 'jpg-to-pdf'],
    ['jpg to pdf', 'jpg-to-pdf'],
    ['image to pdf', 'jpg-to-pdf'],
    ['jpg to pdf converter', 'jpg-to-pdf'],
    ['jpeg to pdf', 'jpg-to-pdf'],
    ['convert jpg images to pdf', 'jpg-to-pdf'],
    ['combine images into pdf', 'jpg-to-pdf'],
    ['browser jpg to pdf', 'jpg-to-pdf'],
    ['no upload jpg to pdf', 'jpg-to-pdf'],
    ['PDF Split', 'pdf-split'],
    ['split pdf', 'pdf-split'],
    ['pdf splitter', 'pdf-split'],
    ['split pdf online', 'pdf-split'],
    ['extract pages from pdf', 'pdf-split'],
    ['pdf page extractor', 'pdf-split'],
    ['save pdf pages', 'pdf-split'],
    ['split pdf by page range', 'pdf-split'],
    ['extract pdf pages', 'pdf-split'],
    ['free pdf splitter', 'pdf-split'],
    ['browser pdf splitter', 'pdf-split'],
    ['Image Resize', 'image-resize'],
    ['image resize', 'image-resize'],
    ['resize image', 'image-resize'],
    ['image resizer', 'image-resize'],
    ['photo resizer', 'image-resize'],
    ['resize jpg', 'image-resize'],
    ['resize png', 'image-resize'],
    ['resize webp', 'image-resize'],
    ['change image dimensions', 'image-resize'],
    ['browser image resizer', 'image-resize'],
    ['no upload image resize', 'image-resize'],
    ['Image Compress', 'image-compress'],
    ['image compress', 'image-compress'],
    ['compress image', 'image-compress'],
    ['image compressor', 'image-compress'],
    ['reduce image size', 'image-compress'],
    ['compress jpg', 'image-compress'],
    ['compress png', 'image-compress'],
    ['compress webp', 'image-compress'],
    ['reduce photo file size', 'image-compress'],
    ['browser image compressor', 'image-compress'],
    ['no upload image compressor', 'image-compress'],
    ['Concrete Quantity Calculator', 'concrete-quantity-calculator'],
    ['concrete calculator', 'concrete-quantity-calculator'],
    ['concrete volume calculator', 'concrete-quantity-calculator'],
    ['rcc quantity calculator', 'concrete-quantity-calculator'],
    ['slab concrete calculator', 'concrete-quantity-calculator'],
    ['beam concrete calculator', 'concrete-quantity-calculator'],
    ['column concrete calculator', 'concrete-quantity-calculator'],
    ['footing concrete calculator', 'concrete-quantity-calculator'],
    ['civil construction calculator', 'concrete-quantity-calculator'],
    ['quantity survey calculator', 'concrete-quantity-calculator'],
    ['Excavation Calculator', 'excavation-calculator'],
    ['excavation calculator', 'excavation-calculator'],
    ['earthwork calculator', 'excavation-calculator'],
    ['trench excavation calculator', 'excavation-calculator'],
    ['footing excavation calculator', 'excavation-calculator'],
    ['foundation excavation calculator', 'excavation-calculator'],
    ['pit excavation calculator', 'excavation-calculator'],
    ['excavation quantity calculator', 'excavation-calculator'],
    ['earthwork quantity calculator', 'excavation-calculator'],
    ['civil engineering excavation calculator', 'excavation-calculator'],
    ['quantity survey excavation calculator', 'excavation-calculator'],
    ['Brickwork Calculator', 'brickwork-calculator'],
    ['brickwork calculator', 'brickwork-calculator'],
    ['brick wall calculator', 'brickwork-calculator'],
    ['brick quantity calculator', 'brickwork-calculator'],
    ['bricks per square metre calculator', 'brickwork-calculator'],
    ['brick masonry calculator', 'brickwork-calculator'],
    ['cement mortar brickwork calculator', 'brickwork-calculator'],
    ['quantity survey brickwork calculator', 'brickwork-calculator'],
    ['Plaster Calculator', 'plaster-calculator'],
    ['plaster calculator', 'plaster-calculator'],
    ['wall plaster calculator', 'plaster-calculator'],
    ['plaster quantity calculator', 'plaster-calculator'],
    ['cement plaster calculator', 'plaster-calculator'],
    ['internal plaster calculator', 'plaster-calculator'],
    ['external plaster calculator', 'plaster-calculator'],
    ['quantity survey plaster calculator', 'plaster-calculator'],
    ['Image Format Converter', 'image-format-converter'],
    ['image format converter', 'image-format-converter'],
    ['image converter', 'image-format-converter'],
    ['convert image online', 'image-format-converter'],
    ['png to webp', 'image-format-converter'],
    ['webp to png', 'image-format-converter'],
    ['webp converter', 'image-format-converter'],
    ['convert jpg png webp', 'image-format-converter'],
    ['free image converter', 'image-format-converter'],
    ['browser image converter', 'image-format-converter'],
    ['image format converter online', 'image-format-converter'],
    ['Image Metadata Remover', 'image-metadata-remover'],
    ['image metadata remover', 'image-metadata-remover'],
    ['remove image metadata', 'image-metadata-remover'],
    ['remove exif data', 'image-metadata-remover'],
    ['exif remover', 'image-metadata-remover'],
    ['photo metadata remover', 'image-metadata-remover'],
    ['remove gps from photo', 'image-metadata-remover'],
    ['remove camera data from image', 'image-metadata-remover'],
    ['strip image metadata', 'image-metadata-remover'],
    ['remove metadata from jpg', 'image-metadata-remover'],
    ['remove metadata from png', 'image-metadata-remover'],
    ['privacy image tool', 'image-metadata-remover'],
    ['Image Watermark', 'image-watermark'],
    ['image watermark', 'image-watermark'],
    ['add watermark to image', 'image-watermark'],
    ['watermark image online', 'image-watermark'],
    ['add text watermark to photo', 'image-watermark'],
    ['photo watermark tool', 'image-watermark'],
    ['watermark jpg', 'image-watermark'],
    ['watermark png', 'image-watermark'],
    ['watermark webp', 'image-watermark'],
    ['add watermark to product image', 'image-watermark'],
    ['free image watermark tool', 'image-watermark'],
    ['browser image watermark', 'image-watermark'],
    ['Image Crop', 'image-crop'],
    ['image crop', 'image-crop'],
    ['crop image online', 'image-crop'],
    ['image cropper', 'image-crop'],
    ['crop jpg', 'image-crop'],
    ['crop png', 'image-crop'],
    ['crop webp', 'image-crop'],
    ['crop photo online', 'image-crop'],
    ['cut image online', 'image-crop'],
    ['pixel crop tool', 'image-crop'],
    ['free image crop tool', 'image-crop'],
    ['browser image cropper', 'image-crop'],
    ['Favicon Generator', 'favicon-generator'],
    ['favicon generator', 'favicon-generator'],
    ['generate favicon', 'favicon-generator'],
    ['favicon maker', 'favicon-generator'],
    ['website favicon generator', 'favicon-generator'],
    ['favicon from image', 'favicon-generator'],
    ['png favicon generator', 'favicon-generator'],
    ['create favicon online', 'favicon-generator'],
    ['favicon sizes', 'favicon-generator'],
    ['website icon generator', 'favicon-generator'],
    ['convert image to favicon', 'favicon-generator'],
    ['browser favicon tool', 'favicon-generator'],
    ['favicon for website', 'favicon-generator'],
  ];
  for (const [query, expected] of cases) {
    it(`"${query}" → ${expected}`, () => expect(top(query)).toBe(expected));
  }

  it('CSV to JSON and JSON to CSV both surface for their shared, order-reversible phrases', () => {
    // "csv to json" and "json to csv" (and their "convert"/"online"/"converter"/"array" variants)
    // tokenize to the exact same bag of words either way round, so this bag-of-words search engine
    // cannot reliably rank one tool over the other for these specific reversible phrases — only a
    // phrase- or order-aware ranking change (a separate engines/search enhancement) could fix that.
    // Both tools stay genuinely findable for them, which is what this asserts, rather than a
    // specific #1 that would be a coin flip and would flake on unrelated future content changes.
    const reversiblePhrases = [
      'json to csv',
      'convert json to csv',
      'json csv converter',
      'json to csv online',
      'json array to csv',
      'free json to csv converter',
      'browser json to csv',
    ];
    for (const phrase of reversiblePhrases) {
      const ids = search(phrase, 2).map((r) => r.id);
      expect(ids, phrase).toContain('json-to-csv');
    }
  });

  it('"logistics calculator" finds all four logistics tools first', () => {
    const ids = search('logistics calculator', 4).map((r) => r.id);
    expect(ids.sort()).toEqual([
      'cbm-calculator',
      'container-loading-calculator',
      'pallet-loading-calculator',
      'volumetric-weight-calculator',
    ]);
  });

  it('returns nothing for an empty query', () => expect(search('  ')).toEqual([]));
  it('is deterministic', () => expect(search('encode')).toEqual(search('encode')));
});
